//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        public int MissionId { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public int MatchId { get; set; }
    
        public virtual Match Match { get; set; }
    }
}
